tabWidth: 2
semi: false
singleQuote: true
singleAttributePerLine: true
printWidth: 80
trailingComma: 'all'
bracketSpacing: true
arrowParens: 'avoid'
proseWrap: 'always'
endOfLine: 'lf'
vueIndentScriptAndStyle: true
